name: JS tests
on: [push, pull_request]

env:
  PNPM_VERSION: 8
  NODE_VERSION: 20

jobs:
  js-linter:
    name: JS linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: ${{ env.PNPM_VERSION }}

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: pnpm
          cache-dependency-path: '_dev/pnpm-lock.yaml'

      - name: Lint JS files
        working-directory: _dev
        run: |
          pnpm install
          pnpm -r lint

  unit-tests:
    name: JS Unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: ${{ env.PNPM_VERSION }}

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: pnpm
          cache-dependency-path: '_dev/pnpm-lock.yaml'

      - name: Install & run
        working-directory: _dev
        run: |
          pnpm install
          pnpm -r test:unit
